### ISSUE TITLE
how can i turn off the "auto delete the class which is not use"?

### ISSUE THREAD

**Issue by brandon3343** [nanch/phpfmt_stable#14]
I'am sorry, I‘am a chese middle school student, maybe I am working hard on my English, when i use this 'ST' plugin: 'phpfmt', when i write use xxxx;"  prepare for using sometimes, the 'phpmft' will delete this 'use xxx', it's make me crazy, how can i turn of it? thank you for solving the problem。

**Comment by brandon3343** [comment]
I had found the config to solving this problem, that is "passes": ["OnlyOrderUseClauses"],。

**Comment by askme-gpt** [comment]
i come accross this problem too .and when i ```"passes": ["OnlyOrderUseClauses"]```  like this ,the phpfmt's format function is out of use . how did you solve this new problem ? my user settings as follows:
```{
	"passes":
	[
		"OnlyOrderUseClauses"
	],
	"version": 1
}
```
