### ISSUE TITLE
phpfmt not available anymore ?

### ISSUE THREAD

**Issue by captain-torche** [nanch/phpfmt_stable#2]
I'm trying to install phpfmt aon a new laptop, but sublimeText 's package controller does not seem to find it.

**Comment by nanch** [comment]
You should be able to install phpfmt. I just installed it on my box from sublime text and it worked fine.

Control + Shift + P
Install Package
phpfmt

**Comment by MarcBrillault** [comment]
Sorry, I forgot to mention I was still using SublimeText 2.

I also [asked on StackOverflow](http://stackoverflow.com/questions/38050293/sublime-text-2s-phpfmt-plugin-is-not-available-anymore/38052349#38052349) and they told it had been removed from the version 2. I upgraded to SublimteText 3 and all works perfectly.
