### ISSUE TITLE
psr4

### ISSUE THREAD

**Issue by liuyuanxiang** [nanch/phpfmt_stable#28]
I found this package does not support psr4. Please improve the code. Thank you!

**Comment by jakebathman** [comment]
Which part of PSR-4 are you looking to have supported, or what are you seeing that isn't working?

**Comment by guttume** [comment]
Opening braces for function and classes should be on their own line as per PSR-4

**Comment by iamhabbeboy** [comment]
Anytime i tried something like this 
`use \Webester\Controllers\IndexController;`
i do got it cleared off on saving the file

**Comment by askme-gpt** [comment]
@iamhabbeboy   
use this in user setting : 
```
	"passes":
	[
		"OnlyOrderUseClauses",
		"ReindentSwitchBlocks",
	],
```

**Comment by wrabit** [comment]
Why isn't the usage of "passes" included in the docs?
