### ISSUE TITLE
get stuck when the php file over 2000 lines

### ISSUE THREAD

**Issue by askme-gpt** [nanch/phpfmt_stable#58]
OS: windows 10 
sublime version:3207
php version :7.3.6
phpfmt version:latest

when I ctrl+s to save the file,it get stuck.how to fix this ?thx
![image](https://user-images.githubusercontent.com/22534808/59022066-ac08e900-887f-11e9-963e-c29019f38ccf.png)

**Comment by askme-gpt** [comment]
I solved this by myself 。 php 7.3.6 has bug， when I change php version to 7.1.31 ,it works fine.

**Comment by JuanDMeGon** [comment]
Hello,
I faced the same in PHP 7.3.7 for files even with less than 250 lines.
I resolved that with PHP 7.2.21.
Just in case, you do not need to change the whole PHP version of your system, you can install an alternative PHP/PHP-CLI version and then configure the "php_bin" for phpfmt in Sublime.
I hope it helps.
