### ISSUE TITLE
Can't save large code after formatting, Using sublime text 3

### ISSUE THREAD

**Issue by ogenyinnaya** [nanch/phpfmt_stable#60]
Please help, sublime text 3 stops responding on trying to save/format large lines of codes (like 1800 lines of code) after formatting.

**Comment by JuanDMeGon** [comment]
Hello,
I faced the same in PHP 7.3.7 for files even with less than 250 lines. It seems to be an issue with PHO 7.3.
I resolved that with PHP 7.2.21. Probably PHP7.1 may work as well.
Just in case, you do not need to change the whole PHP version of your system, you can install an alternative PHP/PHP-CLI version and then configure the "php_bin" for phpfmt in Sublime.
I hope it helps.

**Comment by ogenyinnaya** [comment]
Thank you suggestion was very helpful. Currently using xampp on windows, so I resolved mine by downloading xampp with PHP version PHP 7.2.21 via zip, then have it extracted, rename the php folder name to php7.2.21, then copy it to my xampp folder, then open its php.ini file in my code-editor and rename all appearances of \xampp\php\ to C:\xampp\php7.2.21\ and \xampp\ to  C:\xampp\ and finally within the plugin, ensure php_bin parameter is pointed to php7.2.21 version "php_bin":"C:/xampp/php7.2.21/php.exe"
