### ISSUE TITLE
Format_on_Save dosen't stop 

### ISSUE THREAD

**Issue by mzainzulifqar** [nanch/phpfmt_stable#64]
These are my setting but format_on_save doesnt stop means it keeps formatting the code everytime i save the .php file..!!!!
```    "disable_auto_align": true,
	"format_on_save": false,
	"indent_with_space": false,
	"php_bin": "/usr/local/bin/php",
	"psr1": false,
	"psr2": true,
```

**Comment by resulcaglayan** [comment]
"format_on_save": false,
I use this setting myself. No problem, it works.
