### ISSUE TITLE
Not work with PHP8

### ISSUE THREAD

**Issue by thrass** [nanch/phpfmt_stable#74]
After install/upgrade to PHP8.0.0 but phpfmt not working now. I testing with Sublime Text 4 on Ubuntu Mate 20.04 and OSx 10.14.6 same result!

Any recommendation to resolve this?

My config is basic:

{
	"autocomplete": true,
	"detect_indent": true,
	"enable_auto_align": true,
	"format_on_save": true,
	"ignore": "Parent",
	"indent_with_space": false,
	"php_bin": "/usr/local/bin/php",
	"psr": true, 
	"translate_tabs_to_spaces": true,
	"version": 4,
}

**Comment by tennessine** [comment]
seems the project is dead

**Comment by thrass** [comment]
I solved when install in parallel php7.4 and change the path to php7.4

> {
	"autocomplete": true,
	"detect_indent": true,
	"enable_auto_align": true,
	"format_on_save": true,
	"ignore": "Parent",
	"indent_with_space": false,
	"php_bin": "/usr/bin/php7.4",
	"psr": true,
	"translate_tabs_to_spaces": true,
	"version": 4
}
